import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

import { SessionProvider } from "next-auth/react";

import { auth } from "@/auth";
import { cn } from "@/lib/utils";

import { QueryProvider } from "@/components/provider/query-provider";
import { ToastProvider } from "@/components/provider/toast-provider";
import { ModalProvider } from "@/components/provider/modal-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn(geistSans.className)}>
          <QueryProvider>
            <ModalProvider />
            <ToastProvider />
            {children}
          </QueryProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
